name: notepad
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  encrypt: ^5.0.0
  shared_preferences: ^2.0.6
  easy_localization: ^3.0.0
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9
  fluttertoast: ^8.0.8
  wakelock: ^0.5.2
  in_app_review: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
